name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        
    - name: build and run
      run: |
        gcc -g -Wall code.c -o code
        ./code
