name: C/C++ CI

on:
  push:
    branches: [ markm812-patch-4 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Something but not configure
      run: gcc code.c -o code; ./code

